name: CI/CD

on:
  push:
    branches: [ main ]
    tags: [ "*" ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  unit-testing:
    name: Unit Testing
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v2.4.1
      with:
        node-version: 12.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linting
      run: npm run lint

    - name: Run tests
      run: npm run test-ci

    - name: Upload Test Coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage/

  code-analysis:
    name: Code Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: javascript

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

  deployment:
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'release'
    name: Install and Deploy
    runs-on: ubuntu-latest
    needs: [unit-testing, code-analysis]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 12.x
          cache: 'npm'
          cache-dependency-path: 'functions/package-lock.json'

      - name: Install dependencies
        working-directory: ./functions
        run: npm ci

      - name: Deploy to Google Cloud Functions
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
          name: ${{ github.event_name == 'release' && 'openhabGoogleAssistant' || 'openhabGoogleAssistant_test' }}
          runtime: nodejs12
          source_dir: ./functions
          entry_point: openhabGoogleAssistant
          region: us-central1
          env_vars: OH_HOST=myopenhab.org,OH_PORT=443,OH_PATH=/rest/items/
